project:
  type: website

website:
  title: "OpenRBQM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - tech_team-meetings.qmd

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
