project:
  type: website
website:
  title: "OpenRBQM"
  repo-url: https://github.com/OpenRBQM/OpenRBQM.github.io
  navbar:
    tools:
      - icon: github
        href: https://github.com/OpenRBQM/OpenRBQM.github.io
    left:
      - href: index.qmd
        text: Home
      - href: packages.qmd
        text: Packages
      - href: data.qmd
        text: Data
      - href: news.qmd
        text: News
      - href: help.qmd
        text: Help
      - href: tech_team-meetings.qmd
        text: Tech Team Meetings
    # right:
    #   - text: "{{< fa brands github >}}"
    #   - href: https://github.com/openrbqm
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
