project:
  type: website
website:
  title: "OpenRBQM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: packages.qmd
        text: Packages
      - href: data.qmd
        text: Data
      - href: news.qmd
        text: News
      - href: help.qmd
        text: Help
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
