---
title: "Help"
description: "Get started with OpenRBQM, find answers, and learn how to contribute."
---

# Getting Started

Interested in using {gsm}? Key resources are provided in response to the FAQs below.

## How do I calculate a metric?

See the ["Process Overview"](https://github.com/Gilead-BioStats/gsm.core#process-overview) section and then check out these articles:

-   [Step-by-Step Analysis Workflow Vignette](https://gilead-biostats.github.io/gsm.core/articles/DataAnalysis.html) walks users the step-by-step process for creating metrics (KRIs, QTLs, etc) in {gsm}.
-   [Adverse Event KRI Cookbook Example](https://gilead-biostats.github.io/gsm.kri/dev/examples/Cookbook_AdverseEventKRI.html) provides hands-on examples of how to customize KRI metrics related to Adverse events.

## How do I evaluate a study?

The {gsm} workflow process allows creation of reusable pipelines for study (or even cross-study) data snapshots including data mapping, calculation of multiple metrics and creation of reports. Runtime execution is provided by `{workr}`, while `{gsm.core}` provides the analytical functions used inside those workflows. See the articles below for details and examples.

-   [Data Model Vignette](https://gilead-biostats.github.io/gsm.core/articles/DataModel.html) explains the data pipeline used to calculate multiple metrics and generate study-level reports.
-   [Adverse Event Workflow Example](https://gilead-biostats.github.io/gsm.kri/dev/examples/Cookbook_AdverseEventWorkflow.html) demonstrates how to create a configurable workflow using YAML to define the analysis pipeline.
-   [Reporting Workflow Example](https://gilead-biostats.github.io/gsm.kri/dev/examples/Cookbook_ReportingWorkflow.html) demonstrates a complete workflow from raw data to KRI reports using standard metrics.

## How do I customize my study?

The {gsm} framework is designed to be highly modular and customizable. The sections above show examples of customized metrics and workflows. It's also straightforward to add entire custom modules that add new mappings, metrics and reports. See the vignette below for details.

-   [gsm Extensions Vignette](https://gilead-biostats.github.io/gsm.core/articles/gsmExtensions.html) describes how to extend {gsm.core} by creating new 'modules', including metrics, reports and shiny apps that can be run using the standard gsm pipeline.

## What reports are available for my study?

Here are links to sample reports that are available in the {gsm} family of packages. We're working on adding more all the time and will continue adding examples to this list as they are released.

-   [Site KRI Report](https://gilead-biostats.github.io/gsm.kri/examples/Example_SiteReport.html)
-   [Country KRI Report](https://gilead-biostats.github.io/gsm.kri/examples/Example_CountryReport.html)
-   [Eligibility Report](https://gilead-biostats.github.io/gsm.kri/dev/examples/Example_Eligibility.html)
-   [Cross-Study Site Risk Score Report](https://gilead-biostats.github.io/gsm.kri/dev/examples/Example_CrossStudySRS.html)
-   [QTL Report](https://gilead-biostats.github.io/gsm.qtl/examples/Example_QTL.html)
-   [Good Statistical Monitoring Shiny App](https://rinpharma.shinyapps.io/gsm-app/)

# Contributing

- [Contributing Guide](https://gilead-biostats.github.io/gsm.core/CONTRIBUTING.html) — How to contribute to the OpenRBQM packages.
