---
title: "Tech Team Meeting: 2024-07"
---

# Agenda

::: nonincremental
-   New Members (5 min)
-   GitHub Discussions (15 min)
-   New Ideas (15 min)
-   Next Steps (15 min)
:::

::: notes
-   This will be the rough agenda for every meeting
-   This month we'll likely focus almost entirely on the GitHub discussion.
:::

# New Members

## Jon Harmon

-   Joined Gilead (via Atorus Research) w/ open-source focus
-   Runs the [Data Science Learning Community](https://DSLC.io) / [TidyTuesday](https://tidytues.day)
-   Created [dozens of packages](https://jonthegeek.r-universe.dev/packages)

::: notes
-   I have a lot of experience with:
    -   Software dev
        -   Formerly ran a product team at an educational startup
        -   Lots of experience with Agile & OSS
        -   R packages = my happy place
    -   Community building
    -   Educational materials
-   I'll need help with:
    -   Deciding what to build
    -   User feedback
    -   Prioritization
:::

## Anyone else?

::: notes
-   Can everyone else do a quick intro for me?
    -   Focus on ideas and review, or writing code?
        -   Package-creation experiences?
        -   OSS experience? 
        -   GitHub?
:::

# GitHub Discussions

## CSM Brainstorm

> We need to pick the first CSM module for the team to work on. Please drop ideas/screenshots/links in this chat and we will review at our next team meeting and select our first project!

-   [GitHub](https://github.com/orgs/OpenRBQM/discussions/1)
-   Any other ideas?
-   What problem should we solve first?
-   Roles?

::: notes
-   Get everyone to join the org.
-   Jeremy, do you want to talk through your responses?
-   Any other ideas?
-   Should we start with this?
-   What problem can we solve first?
    -   Is there a particular function that would be helpful?
-   What role does everyone plan to take?
    -   I'll set up repository and get basic package skeleton (including GHA) set up.
    -   Ideally I'd love for everyone to submit & reply to issues.
    -   I can create the whole thing if people want, but I'll need reviews!
:::

# New Ideas

Anything else?


# Next Steps

-   Tasks?
-   Next meeting: 2024-08-28, 11am EDT
    -   Any issues with date/time?
