---
title: "Tech Team Meeting: 2025-03"
---

# Agenda

::: nonincremental
- New Members (5 min)
- Package Updates (25 min)
- New Ideas (5 min)
- Conferences, Workshops, Etc (5 min)
- Next Steps (10 min)
:::


# New Members

## Anyone new?


# Package Updates

## gsm(verse)

[Gilead-BioStats/gsm](https://github.com/Gilead-BioStats/gsm)

- Release to split packages coming soon!
- Workshop at [PHUSE US Connect 2025 Orlando March 18!](https://www.phuse-events.org/attend/frontend/reg/thome.csp?pageID=38599&ef_sel_menu=2971&eventID=61) 

## gsm.app

[Gilead-BioStats/gsm.app](https://github.com/Gilead-BioStats/gsm.app)

Coming soon: 
- New vignette about `fnFetchData()`.
- Slides for workshop

## gsm.digitpref

[OpenRBQM/gsm.digitpref](https://github.com/OpenRBQM/gsm.digitpref)

- In progress: [Statistical part for digit preference](https://github.com/OpenRBQM/gsm.digitpref/pull/16)

## gsm.ae

[OpenRBQM/gsm.ae](https://github.com/OpenRBQM/gsm.ae)

- Now with [issues](https://github.com/OpenRBQM/gsm.ae/issues)!


# New Ideas

- Anything else?


# Conferences, Workshops, Etc

[GitHub Discussion](https://github.com/orgs/OpenRBQM/discussions/11)

- March 16-19: [phuse US connect](https://www.phuse-events.org/attend/frontend/reg/thome.csp?pageID=38599&ef_sel_menu=2971&eventID=61) (Orlando, Florida)
- April 4-9: [ShinyConf2025](https://www.shinyconf.com/) (Online)
- April 9-11: [SCDM 2025 EMEA Conference](https://scdm.org/scdm-2025-emea-conference/) (Brussels, Belgium)
- May 20-21: [phuse CSS](https://advance.hub.phuse.global/wiki/spaces/WEL/pages/38993921/PHUSE+FDA+CSS+2025) (Utrecht, the Netherlands)
- August 2-7: [JSM](https://ww2.amstat.org/meetings/jsm/2025/) (Nashville, Tennessee)
- August 8-10: [useR!2025](https://user2025.r-project.org/) (Durham, North Carolina)
- September 16-19: [posit::conf(2025)](https://reg.conf.posit.co/flow/posit/positconf25/reg/login) (Atlanta, Georgia)


# Next Steps

1. Go to [github.com/orgs/OpenRBQM/discussions](https://github.com/orgs/OpenRBQM/discussions).
2. Reply to an existing thread OR post a new discussion.

- Next meeting: 2025-04-02, 11am EDT
  - Any issues with date/time?
